# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: $script
  config.vm.synced_folder "..", "/vagrant"
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/trusty64"
  config.vm.host_name = "postgresql" 

  # config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
  config.vm.provision :shell, :path => "Vagrant-setup/bootstrap.sh"
  
  # PostgreSQL Server port forwarding
  # N.B. This must match the $PGPORT* variables in Vagrant-setup/bootstrap.sh!
  config.vm.forward_port 5432, 15432
  # and this must match the $APP_API_PORT in the same file.
  config.vm.forward_port 8443, 8443
  # and this for the web-server
  config.vm.forward_port 9443, 9443
end
